
SHOW_MACRO(IUTEST_HAS_CXX_HDR_ANY);
SHOW_MACRO(IUTEST_HAS_CXX_HDR_ARRAY);
SHOW_MACRO(IUTEST_HAS_CXX_HDR_CHARCONV);
SHOW_MACRO(IUTEST_HAS_CXX_HDR_CHRONO);
SHOW_MACRO(IUTEST_HAS_CXX_HDR_CODECVT);
SHOW_MACRO(IUTEST_HAS_CXX_HDR_CSTDINT);
SHOW_MACRO(IUTEST_HAS_CXX_HDR_CUCHAR);
SHOW_MACRO(IUTEST_HAS_CXX_HDR_FILESYSTEM);
SHOW_MACRO(IUTEST_HAS_CXX_HDR_OPTIONAL);
SHOW_MACRO(IUTEST_HAS_CXX_HDR_RANDOM);
SHOW_MACRO(IUTEST_HAS_CXX_HDR_REGEX);
SHOW_MACRO(IUTEST_HAS_CXX_HDR_STRING_VIEW);
SHOW_MACRO(IUTEST_HAS_CXX_HDR_TYPE_TARITS);
SHOW_MACRO(IUTEST_HAS_CXX_HDR_VARIANT);
SHOW_MACRO(IUTEST_HAS_CXX_HDR_VERSION);
SHOW_MACRO(IUTEST_HAS_HDR_CXXABI);
SHOW_MACRO(IUTEST_HAS_HDR_SYSTIME);
#ifdef IUTEST_LIBSTDCXX_VERSION
SHOW_MACRO(IUTEST_LIBSTDCXX_VERSION);
#endif

SHOW_MACRO(IUTEST_HAS_STD_BEGIN_END);
SHOW_MACRO(IUTEST_HAS_STD_DECLVAL);
SHOW_MACRO(IUTEST_HAS_STD_EMPLACE);
SHOW_MACRO(IUTEST_HAS_STD_FILESYSTEM);
SHOW_MACRO(IUTEST_HAS_STD_QUICK_EXIT);
SHOW_MACRO(IUTEST_HAS_STD_STR_TO_VALUE);
SHOW_MACRO(IUTEST_HAS_STD_TO_CHARS);
SHOW_MACRO(IUTEST_HAS_STD_TUPLE);
SHOW_MACRO(IUTEST_HAS_TR1_TUPLE);

#ifdef __GLIBCXX__
SHOW_MACRO(__GLIBCXX__);
#endif
#ifdef __GLIBCPP__
SHOW_MACRO(__GLIBCPP__);
#endif
#ifdef _LIBCPP_VERSION
SHOW_MACRO(_LIBCPP_VERSION);
#endif

#if defined(__cpp_lib_filesystem)
SHOW_MACRO(__cpp_lib_filesystem);
#endif
#if defined(__cpp_lib_experimental_filesystem)
SHOW_MACRO(__cpp_lib_experimental_filesystem);
#endif

