# Copyright (C) 2021, Takazumi Shirayanagi
# This software is released under the new BSD License,
# see LICENSE

CPPCHECK_DEFINES= \
	IUTEST_HAS_CLOCK=1 \
	IUTEST_MAX_PATH=260 \
	__SIZEOF_WCHAR_T__=2 \

CPPCHECK_UNDEFINES= \
	__WIN32__ \
	_WIN32 \
	WIN32 \
	_WIN32_WCE \
	_MSC_VER \
	_MSC_FULL_VER \
	__MT__ \
	_MT \
	_DLL \
	UNICODE \
	_MSVC_LANG \
	_MSVC_TRADITIONAL \
	_CPPUNWIND \
	_CPPRTTI \
	WINAPI_FAMILY \
	WINAPI_FAMILY_APP \
	WINAPI_FAMILY_PHONE_APP \
	WIN32_LEAN_AND_MEAN \
	_NATIVE_WCHAR_T_DEFINED \
	__AFX_H__ \
	MS_CPP_UNITTESTFRAMEWORK \
	__clang__ \
	__clang_analyzer__ \
	IUTEST_CLANG_MAJOR \
	IUTEST_CLANG_MINOR \
	__IBMCPP__ \
	__CYGWIN__ \
	__APPLE__ \
	TARGET_OS_IPHONE \
	__ppc__ \
	__ppc64__ \
	ANDROID \
	__ANDROID__ \
	__CUDACC__ \
	__INTEL_COMPILER \
	COMPILER_ICC \
	__BORLANDC__ \
	__MWERKS__ \
	__MINGW32__ \
	__MINGW64__ \
	__MINGW__ \
	__AVR32__ \
	__avr32__ \
	__arm__ \
	__ARMCC_VERSION \
	_XOPEN_SOURCE \
	_BSD_SOURCE \
	_POSIX_C_SOURCE \
	__BSD_VISIBLE \
	__XSI_VISIBLE \
	__FreeBSD__ \
	sun \
	__sun \
	__SunOS \
	__native_client__ \
	__SGI_STL_PORT \
	_STLPORT_VERSION \
	_STLP_LONG_LONG \
	__USE_MINGW_ANSI_STDIO \
	__MAC_OS_X_VERSION_MIN_REQUIRED \
	__STDC_WANT_SECURE_LIB__ \
	IUTEST_BUILD_DOXYGEN \
	IUTEST_OS_WINDOWS_MINGW \
	IUTEST_OS_FREEBSD \
	IUTEST_OS_LINUX_ANDROID \
	IUTEST_OS_NACL \
	IUTEST_COND_UNLIKELY \
	IUTEST_ATTRIBUTE_LIKELY_ \
	IUTEST_ATTRIBUTE_UNLIKELY_ \
	IUTEST_ATTRIBUTE_INIT_PRIORITY_ \
	IUTEST_ATTRIBUTE_NO_SANITIZE_ADDRESS \
	IUTEST_ATTRIBUTE_NO_SANITIZE_MEMORY \
	IUTEST_ATTRIBUTE_NO_SANITIZE_THREAD \
	IUTEST_HAS_ATTRIBUTE_DEPRECATED \
	__WANDBOX__ \
	GTEST_OS_SOLARIS \
	GTEST_OS_WINDOWS \
	GTEST_OS_WINDOWS_MINGW \
	_IUTEST_DEBUG \

# C++20

CPPCHECK_DEFINES+= \
	IUTEST_CPLUSPLUS=202002L \
	__GXX_EXPERIMENTAL_CXX0X__=1 \

CPPCHECK_DEFINES+= \
	IUTEST_HAS_OVERRIDE_AND_FINAL=1 \
	IUTEST_CXX_OVERRIDE=override \
	IUTEST_CXX_FINAL=final \

CPPCHECK_DEFINES+= \
	IUTEST_HAS_LONG_DOUBLE=1 \

# gtest
CPPCHECK_DEFINES+= \
	GTEST_MAJORVER=0x01 \
	GTEST_MINORVER=0x10	\
	GTEST_MICROVER=0x00	\
	GTEST_REVISION=0x00	\
	GTEST_BUILD=0x00	\
	GTEST_LATEST=0		\

CPPCHECK_UNDEFINES+= \
	IUTEST_USE_GTEST


# suppress check
CPPCHECK_SUPPRESS= \
	syntaxError \
	missingIncludeSystem \
	ConfigurationNotChecked \
	knownConditionTrueFalse:*/iutest_internal_defs.hpp \
	unusedPrivateFunction \
	unmatchedSuppression
