cirrus_gcc_test_task:
  only_if: &default-condition $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'develop' || $CIRRUS_BRANCH =~ 'feature/.*' || $CIRRUS_BRANCH =~ 'cirrusci/.*' || $CIRRUS_BASE_BRANCH != ''
  auto_cancellation: true
  container:
    image: gcc:latest
  env:
    matrix:
      STDFLAG: -std=c++14
      STDFLAG: -std=c++17
      #STDFLAG: -std=c++2a
  test_script: cd test && make -j4 showcxxversion default && make test

#cirrus_use_gtest_task:
#  env:
#    USE_GTEST: 1
#  container:
#    image: srzzumix/googletest:latest
#  test_script: cd test && make -j4 showcxxversion default && make test

cirrus_osx_14_test_task: &osx_task
  only_if: *default-condition
  auto_cancellation: true
  osx_instance:
    image: mojave-xcode-10.1
    # image: high-sierra-xcode-9.4.1
  env:
    STDFLAG: -std=c++14
  test_script: cd test && make -j4 showcxxversion default && make test

cirrus_osx_17_test_task:
  <<: *osx_task
  env:
    STDFLAG: -std=c++17
  depends_on:
    - cirrus_osx_14_test

# cirrus_worker_info_task:
#   container:
#     image: gcc:latest
#   test_script: env

cirrus_freebsd_clang_test_task:
  freebsd_instance:
    image: freebsd-11-2-release-amd64
  env:
    matrix:
      STDFLAG: -std=c++14
      STDFLAG: -std=c++17
      #STDFLAG: -std=c++2a
  version_script: cd test && make -j4 showcxxversion
  test_script: cd test && make -j4 && make test

