kind: pipeline
name: benchmark_test

trigger:
  branch:
    - master
    - develop
    - feature/*
    - drone/*

steps:
- name: bench
  image: gcc
  commands:
    - cd test
    - make -C benchmark
    - make bench
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: SLACK_WEBHOOK
    channel: ci
    username: drone
    icon_url: https://raw.githubusercontent.com/drone/brand/master/logos/png/drone-logo-dark_256.png
  when:
    status: [ success, failure ]

---
kind: pipeline
name: build_docker

trigger:
  branch:
    - master
    - develop
    - feature/*
    - drone/*
  event:
    - push

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: tools/docker/Dockerfile
    repo: srzzumix/iutest
    dry_run: true
