kind: pipeline
name: gtest-compatible-released

trigger:
  branch:
    - master
    - develop
    - feature/*
    - fix/*
    - drone/*

steps:
- name: release-1.8.1
  image: srzzumix/googletest:release-1.8.1
  environment:
    GTEST_EXPECT_VERSION: 0x01080100
  commands: &gtest-compatible-commands
    - "cd test"
    - "make showcxxversion"
    - "make USE_GTEST=1             GTEST_EXPECT_VER=${GTEST_EXPECT_VERSION} test"
    - "make USE_GTEST=1 USE_GMOCK=1 GTEST_EXPECT_VER=${GTEST_EXPECT_VERSION} test"
- name: release-1.8.0
  image: srzzumix/googletest:release-1.8.0
  environment:
    GTEST_EXPECT_VERSION: 0x01080000
  commands: *gtest-compatible-commands
- name: release-1.7.0
  image: srzzumix/googletest:release-1.7.0
  environment:
    GTEST_EXPECT_VERSION: 0x01070000
  commands: *gtest-compatible-commands
- name: release-1.6.0
  image: srzzumix/googletest:release-1.6.0
  environment:
    GTEST_EXPECT_VERSION: 0x01060000
  commands: *gtest-compatible-commands
- name: release-1.5.0
  image: srzzumix/googletest:release-1.5.0
  environment:
    GTEST_EXPECT_VERSION: 0x01050000
  commands: *gtest-compatible-commands
# https://github.com/srz-zumix/docker-googletest/issues/2
# - name: release-1.4.0
#   image: srzzumix/googletest:release-1.4.0
#   environment:
#     GTEST_EXPECT_VERSION: 0x01040000
#   commands: *gtest-compatible-commands
#  google test 1.3.0 or less is not supported...
# - name: release-1.3.0
#   image: srzzumix/googletest:release-1.3.0
#   environment:
#     GTEST_EXPECT_VERSION: 0x01030000
#   commands: *gtest-compatible-commands
# - name: release-1.2.1
#   image: srzzumix/googletest:release-1.2.1
#   environment:
#     GTEST_EXPECT_VERSION: 0x01020100
#   commands: *gtest-compatible-commands
# - name: release-1.2.0
#   image: srzzumix/googletest:release-1.2.0
#   environment:
#     GTEST_EXPECT_VERSION: 0x01020000
#   commands: *gtest-compatible-commands
# - name: release-1.1.0
#   image: srzzumix/googletest:release-1.1.0
#   environment:
#     GTEST_EXPECT_VERSION: 0x01010000
#   commands: *gtest-compatible-commands
# - name: release-1.0.0
#   image: srzzumix/googletest:release-1.0.0
#   environment:
#     GTEST_EXPECT_VERSION: 0x01000000
#   commands: *gtest-compatible-commands
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: SLACK_WEBHOOK
    channel: ci
    username: drone
    icon_url: https://raw.githubusercontent.com/drone/brand/master/logos/png/drone-logo-dark_256.png
  when:
    status: [ failure ]

---
kind: pipeline
name: gtest-version-detect

trigger:
  branch:
    - master
    - develop
    - feature/*
    - drone/*

steps:
- name: latest
  image: srzzumix/googletest:latest
  environment:
    GTEST_EXPECT_VERSION: 0x01080100
  commands:
    - "cd test"
    - "make showcxxversion"
    - "make USE_GTEST=1             GTEST_EXPECT_VER=${GTEST_EXPECT_VERSION} GTEST_EXPECT_LATEST=1 gtest-version"
    - "make USE_GTEST=1 USE_GMOCK=1 GTEST_EXPECT_VER=${GTEST_EXPECT_VERSION} GTEST_EXPECT_LATEST=1 gtest-version"
  when:
    branch:
      exclude:
        - master
- name: release-1.8.1
  image: srzzumix/googletest:release-1.8.1
  environment:
    GTEST_EXPECT_VERSION: 0x01080100
  commands: &gtest-version-detect-commands
    - "cd test"
    - "make showcxxversion"
    - "make USE_GTEST=1             GTEST_EXPECT_VER=${GTEST_EXPECT_VERSION} gtest-version"
    - "make USE_GTEST=1 USE_GMOCK=1 GTEST_EXPECT_VER=${GTEST_EXPECT_VERSION} gtest-version"
- name: release-1.8.0
  image: srzzumix/googletest:release-1.8.0
  environment:
    GTEST_EXPECT_VERSION: 0x01080000
  commands: *gtest-version-detect-commands
- name: release-1.7.0
  image: srzzumix/googletest:release-1.7.0
  environment:
    GTEST_EXPECT_VERSION: 0x01070000
  commands: *gtest-version-detect-commands
- name: release-1.6.0
  image: srzzumix/googletest:release-1.6.0
  environment:
    GTEST_EXPECT_VERSION: 0x01060000
  commands: *gtest-version-detect-commands
- name: release-1.5.0
  image: srzzumix/googletest:release-1.5.0
  environment:
    GTEST_EXPECT_VERSION: 0x01050000
  commands: *gtest-version-detect-commands
- name: release-1.4.0
  image: srzzumix/googletest:release-1.4.0
  environment:
    GTEST_EXPECT_VERSION: 0x01040000
  commands: *gtest-version-detect-commands
#  google test 1.3.0 or less is not supported...
# - name: release-1.3.0
#   image: srzzumix/googletest:release-1.3.0
#   environment:
#     GTEST_EXPECT_VERSION: 0x01030000
#   commands: *gtest-version-detect-commands
# - name: release-1.2.1
#   image: srzzumix/googletest:release-1.2.1
#   environment:
#     GTEST_EXPECT_VERSION: 0x01020100
#   commands: *gtest-version-detect-commands
# - name: release-1.2.0
#   image: srzzumix/googletest:release-1.2.0
#   environment:
#     GTEST_EXPECT_VERSION: 0x01020000
#   commands: *gtest-version-detect-commands
# - name: release-1.1.0
#   image: srzzumix/googletest:release-1.1.0
#   environment:
#     GTEST_EXPECT_VERSION: 0x01010000
#   commands: *gtest-version-detect-commands
# - name: release-1.0.0
#   image: srzzumix/googletest:release-1.0.0
#   environment:
#     GTEST_EXPECT_VERSION: 0x01000000
#   commands: *gtest-version-detect-commands
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: SLACK_WEBHOOK
    channel: ci
    username: drone
    icon_url: https://raw.githubusercontent.com/drone/brand/master/logos/png/drone-logo-dark_256.png
  when:
    status: [ failure ]

# ---
# kind: pipeline
# name: build_docker

# trigger:
#   branch:
#     - master
#     - develop
#     - feature/*
#     - drone/*
#   event:
#     - push

# steps:
# - name: build
#   image: plugins/docker
#   settings:
#     dockerfile: tools/docker/Dockerfile
#     repo: srzzumix/iutest
#     dry_run: true
