kind: pipeline
name: benchmark_test

clone:
  depth: 1

steps:
- name: bench
  image: gcc
  commands:
    - cd test
    - make -C benchmark
    - make bench

---
kind: pipeline
name: build_docker

steps:
- name: build
  image: docker
  commands:
    - docker build tools/docker/Dockerfile

