kind: pipeline
name: benchmark_test

steps:
- name: bench
  image: gcc
  commands:
    - cd test
    - make -C benchmark
    - make bench
  when:
    branch:
      - master
      - develop
      - feature/*
      - drone/*

---
kind: pipeline
name: build_docker

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: tools/docker/Dockerfile
    repo: srzzumix/iutest
    dry_run: true
  when:
    branch:
      - master
      - develop
      - feature/*
      - drone/*
    event:
      - push
- name: bench
  image: srzzumix/iutest
  commands:
    - make -j4 -C test test

