tasks:
  centos-tests:
    image: srzzumix/gcc3:centos5
    commands:
      - find . -type f \( -name \*.hpp -or -name \*.cpp \) | xargs nkf --overwrite --oc=UTF-8
      - make -C test -j4
      - make -C test test
  # ubuntu-tests:
  #   image: srzzumix/gcc3:ubuntu
  #   commands:
  #     - find . -type f \( -name \*.hpp -or -name \*.cpp \) | xargs nkf --overwrite --oc=UTF-8
  #     - make -C test -j4
  #     - make -C test test
