version: v2

tasks:
  build-image:
    steps:
      - checkout
      - docker/build:
          image: iutest/razorops_test
          push: false
          tags: [ "latest" ]
          dockerfile: .ci/docker/centos/Dockerfile

  test:
    depends: [build-image]
    runner: iutest/razorops_test
    steps:
      - checkout
      - commands:
          - uname -a
          - cd test
          - make OUTPUTXML=junit
          - make OUTPUTXML=junit test
          - make report
          - cd ..
      - reports/junit:
          paths: [ "test/*.xml" ]

  lint-editorconfig:
    steps:
    - checkout
    - cache/pull: npm-editor-{{ checksum "package.json" }}
    - commands:
      - npm install
      - npm run lint:editorconfig
    - cache/push:
        key: npm-editor-{{ checksum "package.json" }}
        paths: [node_modules]

trigger:
  ## triggers pipeline only on feature branches and on tags (mind the prefix)
  when: branch in ('master', 'develop') || branch =~ 'razorops.*'
