version: v2

global:
  runner:
    os_image: ubuntu

tasks:
  build-image:
    steps:
      - checkout
      - docker/build:
          image: iutest/razorops_test
          push: false
          tags: [ "latest" ]
          dockerfile: .ci/docker/centos/Dockerfile
          context: .
    when: &condition >
      branch in ('master', 'develop') ||
      branch =~ 'razorops.*'

  test:
    depends: [build-image]
    containers:
      - image: iutest/razorops_test
    steps:
      - commands:
          - echo ${CI_REPO_BRANCH}
      - checkout
      - commands:
          # - cd /iutest/test
          - uname -a
          - cd test
          - make OUTPUTXML=junit
          - make OUTPUTXML=junit test
          - make report
          - cd ..
      - reports/junit:
          paths: [ "test/*.xml" ]
    when: *condition

trigger:
  ## triggers pipeline only on feature branches and on tags (mind the prefix)
  if: branch in ('master', 'develop') || branch =~ /razorops.*/

workflows:
  - name: centos-test
    tasks:
      - build-image
      - test
