version: v2

tasks:
  test:
    containers:
      - image: srzzumix/gcc3:centos5
    steps:
      - checkout
      - commands:
          - uname -a
          # gcc 3 is not support UTF8-BOM
          - find . -type f \( -name \*.hpp -or -name \*.cpp -or -name \*.ipp \) -exec sed -i -e '1s/^\xEF\xBB\xBF//' {} \;
          - cd test
          - make showcxxversion showcxxmacros
          - make -j4  OUTPUTXML=junit
          - make test OUTPUTXML=junit
          - make report
      # Note:
      # Failed to check if bucket(throbbing-shape-1474) exists: Missing fields in request.
      # bucket throbbing-shape-1474: Missing fields in request.
      # - reports/junit:
      #     paths: [ "test/*.xml" ]

  lint-editorconfig:
    depends: [test]
    steps:
    - checkout
    # - cache/pull:
    #     key: npm-cache-[[ checksum "package-lock.json" ]]
    #     fallback_key: npm-cache-
    - commands:
      - npm install
      - npm run lint:editorconfig
    # - cache/push:
    #     key: npm-cache-[[ checksum "package-lock.json" ]]
    #     paths: [node_modules]

trigger:
  ## triggers pipeline only on feature branches and on tags (mind the prefix)
  when: branch in ('master', 'develop') || branch =~ 'razorops.*'

# Note:
# workflows seems to be unsupported GitHub Checks
# workflows:
#   - name: centos-test
#     tasks:
#       - build-image
#       - test
#   - name: lint
#     tasks:
#       - lint-editorconfig
