version: v2

tasks:
  # build-image:
  #   steps:
  #     - checkout
  #     - docker/build:
  #         image: iutest/razorops_test
  #         push: false
  #         tags: [ "latest" ]
  #         dockerfile: .ci/docker/centos/Dockerfile

  # test:
  #   depends: [build-image]
  #   containers:
  #     - image: iutest/razorops_test
  #   steps:
  #     - checkout
  #     - commands:
  #         - uname -a
  #         - cd test
  #         - make OUTPUTXML=junit
  #         - make OUTPUTXML=junit test
  #         - make report
  #         - cd ..
  #     # Note:
  #     # Failed to check if bucket(throbbing-shape-1474) exists: Missing fields in request.
  #     # bucket throbbing-shape-1474: Missing fields in request.
  #     # - reports/junit:
  #     #     paths: [ "test/*.xml" ]

  lint-editorconfig:
    steps:
    - checkout
    # - cache/pull:
    #     key: npm-cache-[[ checksum "package-lock.json" ]]
    #     fallback_key: npm-cache-
    - commands:
      - npm install
      - npm run lint:editorconfig
    # - cache/push:
    #     key: npm-cache-[[ checksum "package-lock.json" ]]
    #     paths: [node_modules]

trigger:
  ## triggers pipeline only on feature branches and on tags (mind the prefix)
  when: branch in ('master', 'develop') || branch =~ 'razorops.*'

# Note:
# workflows seems to be unsupported GitHub Checks
# workflows:
#   - name: centos-test
#     tasks:
#       - build-image
#       - test
#   - name: lint
#     tasks:
#       - lint-editorconfig
