tasks:
  build-image:
    type: build
    image: iutest/razorops_test
    push: false
    tags: ["latest"]
    dockerfile: .ci/docker/centos/Dockerfile
    context: .

  test:
    image: iutest/razorops_test
    commands:
      - cd /iutest/test
      - ls
      - make clean
      - make
      - make test

  centos7:
    image: centos/devtoolset-7-toolchain-centos7:latest
    commands:
      - make -C test clean
      - make -C test
      - make -C test test
    when: &condition >
      branch in ('master', 'develop') ||
      branch =~ 'razorops.*'

  # gcc3-centos5:
  #   image: srzzumix/gcc3:centos5
  #   commands:
  #     - find . -type f \( -name \*.hpp -or -name \*.cpp -or -name \*.ipp \) -exec sed -i -e '1s/^\xEF\xBB\xBF//' {} \;
  #     - make -C test
  #     - make -C test test
  #   when: *condition
