version: v2

tasks:
  test:
    containers:
      - image: srzzumix/gcc3:centos5
    steps:
      - checkout
      - commands:
          # gcc 3 is not support UTF8-BOM
          - find . -type f \( -name \*.hpp -or -name \*.cpp -or -name \*.ipp \) -exec sed -i -e '1s/^\xEF\xBB\xBF//' {} \;
          - cd test
          - make showcxxversion showcxxmacros
          - make
          - make test
          - make report
      # Note:
      # Failed to check if bucket(throbbing-shape-1474) exists: Missing fields in request.
      # bucket throbbing-shape-1474: Missing fields in request.
      # - reports/junit:
      #     paths: [ "test/*.xml" ]

  gcc-fanalyzer:
    steps:
    - checkout
    - commands:
      - export DEFS="-fanalyzer -Wno-analyzer-possible-null-argument -Wno-analyzer-possible-null-dereference"
      - make -C test clean
      - make -C test showcxxversion
      - make -C test showcxxmacros
      - make -C test check_stdlib
      - make -C test -j1
      - make -C test test


  lint-editorconfig:
    steps:
    - checkout
    # - cache/pull:
    #     key: npm-cache-[[ checksum "package-lock.json" ]]
    #     fallback_key: npm-cache-
    - commands:
      - npm install
      - npm run lint:editorconfig
    # - cache/push:
    #     key: npm-cache-[[ checksum "package-lock.json" ]]
    #     paths: [node_modules]

trigger:
  ## triggers pipeline only on feature branches and on tags (mind the prefix)
  when: branch in ('master', 'develop') || branch =~ 'razorops.*'

# Note:
# workflows seems to be unsupported GitHub Checks
workflows:
  - name: gcc3-test
    tasks:
      - test
  - name: gcc-fanalyzer
    tasks:
      - gcc-fanalyzer
  - name: lint
    tasks:
      - lint-editorconfig
