tasks:
  # ubuntu-tests:
  #   image: srzzumix/gcc3:ubuntu
  #   commands:
  #     - find . -type f \( -name \*.hpp -or -name \*.cpp -or -name \*.ipp \) | xargs nkf --overwrite --oc=UTF-8
  #     - make -C test -j4
  #     - make -C test test
  centos:
    # image: centos/devtoolset-7-toolchain-centos7:latest
    image: gcc
    commands:
      - make -C test
      - make -C test test
    when: &condition >
      branch in ('master', 'develop') ||
      branch =~ 'razorops.*'

  # gcc3-centos5:
  #   image: srzzumix/gcc3:centos5
  #   commands:
  #     - find . -type f \( -name \*.hpp -or -name \*.cpp -or -name \*.ipp \) -exec sed -i -e '1s/^\xEF\xBB\xBF//' {} \;
  #     - make -C test -j4
  #     - make -C test test
  #   when: *condition
