version: v2

global:
  runner:
    os_image: ubuntu

tasks:
  build-image:
    steps:
    - checkout
    - docker/build:
        image: iutest/razorops_test
        push: false
        tags: [ "latest" ]
        dockerfile: .ci/docker/centos/Dockerfile
        context: .
    when: &condition >
      branch in ('master', 'develop') ||
      branch =~ 'razorops.*'

  test:
    containers:
      - image: iutest/razorops_test
    steps:
      - checkout
      - commands:
          # - cd /iutest/test
          - cd test
          - make OUTPUTXML=junit
          - make OUTPUTXML=junit test
          - make report
          - make clean
      # - reports/junit:
      #     paths: test/*.xml
    when: *condition

workflows:
  - name: centos-test
    tasks:
      - build-image
      - test
