version: '1.0'
stages:
  - checkout
  - build
  - prepare
  - test1
  - test2
  - test3

steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    stage: checkout
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
  BuildingDockerImage:
    title: Building Docker Image
    stage: build
    type: build
    image_name: srz-zumix/iutest
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: ./tools/docker/Dockerfile
  PrepareUnitTests:
    title: Prepare
    stage: prepare
    image: gcc:9
    commands:
      - make -C test clean
      - make -C test prepare
  RunningUnitTests:
    type: parallel
    stage: test1
    steps:
      BasicTest-gcc9: &basic_test
        title: Running Basic Tests - gcc9
        image: gcc:9
        environment:
          - OUTDIR=gcc9
        commands:
          - rm -rf test/${OUTDIR} || true
          - mkdir test/${OUTDIR}
          - make -C test -j4
          - make -C test test
      BasicTest-gcc8:
        <<: *basic_test
        title: Running Basic Tests - gcc8
        image: gcc:8
        environment:
          - OUTDIR=gcc8
  RunningUnitTests2:
    type: parallel
    stage: test2
    steps:
      BasicTest-gcc7:
        <<: *basic_test
        title: Running Basic Tests - gcc7
        image: gcc:7
        environment:
          - OUTDIR=gcc7
  BenchmarkTest:
    title: Running Benchmark Tests
    stage: test3
    image: '${{BuildingDockerImage}}'
    working_directory: IMAGE_WORK_DIR
    entry_point:
      - /bin/sh
      - /codefresh/volume/cf-generated/unit_test_script
    create_file:
      path: /codefresh/volume/cf-generated
      name: unit_test_script
      content: |-
        cd /codefresh/volume/iutest
        cd test
        make -C benchmark
        make bench
    when:
      steps:
       - name: Running Basic Tests - gcc9
         on:
           - success
       - name: Running Basic Tests - gcc8
         on:
           - success
       - name: Running Basic Tests - gcc7
         on:
           - success
    on_success:
      metadata:
        set:
          - '${{BuildingDockerImage.imageId}}':
              - CF_QUALITY: true
    on_fail:
      metadata:
        set:
          - '${{BuildingDockerImage.imageId}}':
              - CF_QUALITY: false
