version: '1.0'
stages:
  - checkout
  - build
  - prepare
  - build_all_unit_tests
  - build_other_unit_tests
  - run_tests
  - benchmark

steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    stage: checkout
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    when: &skip_condition
      condition:
        all:
          noSkipCiInCommitMessage1: 'includes(lower("${{CF_COMMIT_MESSAGE}}"), "skip ci") == false'
          noSkipCiInCommitMessage2: 'includes(lower("${{CF_COMMIT_MESSAGE}}"), "ci skip") == false'
  BuildingDockerImage:
    title: Building Docker Image
    stage: build
    type: build
    image_name: srzzumix/iutest_dev_env
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: ./tools/docker/Dockerfile
    when: *skip_condition
  PrepareUnitTests:
    title: Prepare
    stage: prepare
    image: gcc:9
    commands:
      - cf_export GGC_MIN_EXPAND=4
      - cf_export GGC_MIN_HEAPSIZ=32768
      - cf_export CI_NODEBUG=1
      - make -C test clean
      - make -C test prepare
    when: *skip_condition
  BuildAllUnitTests:
    type: parallel
    stage: build_all_unit_tests
    when: *skip_condition
    steps:
      BuildAllUnitTest_gcc9: &build_all_unit_test
        title: Build Basic all_tests - gcc9
        image: gcc:9
        environment:
          - OUTDIR=gcc9
        commands:
          - rm -rf test/${OUTDIR} || true
          - mkdir test/${OUTDIR}
          - make -C test all_tests_build
      BuildAllUnitTest_gcc8:
        <<: *build_all_unit_test
        title: Build Basic all_tests - gcc8
        image: gcc:8
        environment:
          - OUTDIR=gcc8
      # BuildAllUnitTest_gcc7:
      #   <<: *build_all_unit_test
      #   title: Build Basic all_tests - gcc7
      #   image: gcc:7
      #   environment:
      #     - OUTDIR=gcc7
  BuildOtherUnitTests:
    type: parallel
    stage: build_other_unit_tests
    steps:
      BuildOtherUnitTest_gcc9: &build_other_unit_tests
        image: gcc:9
        environment:
          - OUTDIR=gcc9
        commands:
          - make -C test
        when:
          steps:
          - name: BuildAllUnitTest_gcc9
            on:
              - success
      BuildOtherUnitTest_gcc8:
        <<: *build_other_unit_tests
        image: gcc:8
        environment:
          - OUTDIR=gcc8
        when:
          steps:
          - name: BuildAllUnitTest_gcc8
            on:
              - success
      # BuildOtherUnitTest_gcc7:
      #   <<: *build_other_unit_tests
      #   image: gcc:7
      #   environment:
      #     - OUTDIR=gcc7
      #   when:
      #     steps:
      #     - name: BuildAllUnitTest_gcc7
      #       on:
      #         - success
  RunTests:
    type: parallel
    stage: run_tests
    steps:
      RunTest_gcc9: &run_test
        image: gcc:9
        environment:
          - OUTDIR=gcc9
        commands:
          - make -C test test && make -C test report
        when:
          steps:
          - name: BuildOtherUnitTest_gcc9
            on:
              - success
      RunTest_gcc8:
        <<: *run_test
        image: gcc:8
        environment:
          - OUTDIR=gcc8
        when:
          steps:
          - name: BuildOtherUnitTest_gcc8
            on:
              - success
      # RunTest_gcc7:
      #   <<: *run_test
      #   image: gcc:7
      #   environment:
      #     - OUTDIR=gcc7
      #   when:
      #     steps:
      #     - name: BuildOtherUnitTest_gcc7
      #       on:
      #         - success
  Benchmark:
    title: Running Benchmark Tests
    stage: benchmark
    image: '${{BuildingDockerImage}}'
    working_directory: IMAGE_WORK_DIR
    entry_point:
      - /bin/sh
      - /codefresh/volume/cf-generated/unit_test_script
    create_file:
      path: /codefresh/volume/cf-generated
      name: unit_test_script
      content: |-
        cd /codefresh/volume/iutest
        cd test
        make -C benchmark
        make bench
    when:
      steps:
        - name: RunningUnitTest_gcc9
          on:
            - success
        - name: RunningUnitTest_gcc8
          on:
            - success
        # - name: RunningUnitTest_gcc7
        #   on:
        #     - success
    on_success:
      metadata:
        set:
          - '${{BuildingDockerImage.imageId}}':
              - CF_QUALITY: true
    on_fail:
      metadata:
        set:
          - '${{BuildingDockerImage.imageId}}':
              - CF_QUALITY: false
