//======================================================================
//-----------------------------------------------------------------------
/**
 * @file		iutest_template_util_undef.hpp
 * @brief		iris unit test template ヘルパー define undef ファイル
 *
 * @author		t.sirayanagi
 * @version		1.0
 *
 * @par			copyright
 * Copyright (C) 2012, Takazumi Shirayanagi\n
 * The new BSD License is applied to this software.
 * see LICENSE
*/
//-----------------------------------------------------------------------
//======================================================================
#ifndef INCG_IRIS_iutest_template_util_undef_HPP_
#define INCG_IRIS_iutest_template_util_undef_HPP_

//======================================================================
// define

#undef IUTEST_TEMPLATE_UTIL_TEMPLATES1
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES2
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES3
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES4
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES5
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES6
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES7
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES8
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES9
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES10
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES11
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES12
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES13
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES14
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES15
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES16
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES17
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES18
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES19
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES20

#undef IUTEST_TEMPLATE_UTIL_ARGS1
#undef IUTEST_TEMPLATE_UTIL_ARGS2
#undef IUTEST_TEMPLATE_UTIL_ARGS3
#undef IUTEST_TEMPLATE_UTIL_ARGS4
#undef IUTEST_TEMPLATE_UTIL_ARGS5
#undef IUTEST_TEMPLATE_UTIL_ARGS6
#undef IUTEST_TEMPLATE_UTIL_ARGS7
#undef IUTEST_TEMPLATE_UTIL_ARGS8
#undef IUTEST_TEMPLATE_UTIL_ARGS9
#undef IUTEST_TEMPLATE_UTIL_ARGS10
#undef IUTEST_TEMPLATE_UTIL_ARGS11
#undef IUTEST_TEMPLATE_UTIL_ARGS12
#undef IUTEST_TEMPLATE_UTIL_ARGS13
#undef IUTEST_TEMPLATE_UTIL_ARGS14
#undef IUTEST_TEMPLATE_UTIL_ARGS15
#undef IUTEST_TEMPLATE_UTIL_ARGS16
#undef IUTEST_TEMPLATE_UTIL_ARGS17
#undef IUTEST_TEMPLATE_UTIL_ARGS18
#undef IUTEST_TEMPLATE_UTIL_ARGS19
#undef IUTEST_TEMPLATE_UTIL_ARGS20

#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS1
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS2
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS3
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS4
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS5
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS6
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS7
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS8
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS9
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS10
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS11
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS12
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS13
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS14
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS15
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS16
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS17
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS18
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS19
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS20

#undef IUTEST_TEMPLATE_UTIL_VALUES1
#undef IUTEST_TEMPLATE_UTIL_VALUES2
#undef IUTEST_TEMPLATE_UTIL_VALUES3
#undef IUTEST_TEMPLATE_UTIL_VALUES4
#undef IUTEST_TEMPLATE_UTIL_VALUES5
#undef IUTEST_TEMPLATE_UTIL_VALUES6
#undef IUTEST_TEMPLATE_UTIL_VALUES7
#undef IUTEST_TEMPLATE_UTIL_VALUES8
#undef IUTEST_TEMPLATE_UTIL_VALUES9
#undef IUTEST_TEMPLATE_UTIL_VALUES10
#undef IUTEST_TEMPLATE_UTIL_VALUES11
#undef IUTEST_TEMPLATE_UTIL_VALUES12
#undef IUTEST_TEMPLATE_UTIL_VALUES13
#undef IUTEST_TEMPLATE_UTIL_VALUES14
#undef IUTEST_TEMPLATE_UTIL_VALUES15
#undef IUTEST_TEMPLATE_UTIL_VALUES16
#undef IUTEST_TEMPLATE_UTIL_VALUES17
#undef IUTEST_TEMPLATE_UTIL_VALUES18
#undef IUTEST_TEMPLATE_UTIL_VALUES19
#undef IUTEST_TEMPLATE_UTIL_VALUES20

#ifdef INCG_IRIS_iutest_template_util_defs_HPP_
#  undef INCG_IRIS_iutest_template_util_defs_HPP_
#endif

#endif
