//======================================================================
//-----------------------------------------------------------------------
/**
 * @file		iutest_function_traits_defs.hpp
 * @brief		iris unit test function type traits ヘルパー定義 ファイル
 *
 * @author		t.sirayanagi
 * @version		1.0
 *
 * @par			copyright
 * Copyright (C) 2012, Takazumi Shirayanagi\n
 * The new BSD License is applied to this software.
 * see LICENSE
*/
//-----------------------------------------------------------------------
//======================================================================
#ifndef INCG_IRIS_iutest_function_traits_defs_HPP_
#define INCG_IRIS_iutest_function_traits_defs_HPP_

//======================================================================
// define
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES1		typename T0
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES2		IUTEST_FUNCTION_TEMPLATE_TEMPLATES1, typename T1
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES3		IUTEST_FUNCTION_TEMPLATE_TEMPLATES2, typename T2
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES4		IUTEST_FUNCTION_TEMPLATE_TEMPLATES3, typename T3
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES5		IUTEST_FUNCTION_TEMPLATE_TEMPLATES4, typename T4
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES6		IUTEST_FUNCTION_TEMPLATE_TEMPLATES5, typename T5
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES7		IUTEST_FUNCTION_TEMPLATE_TEMPLATES6, typename T6
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES8		IUTEST_FUNCTION_TEMPLATE_TEMPLATES7, typename T7
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES9		IUTEST_FUNCTION_TEMPLATE_TEMPLATES8, typename T8
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES10	IUTEST_FUNCTION_TEMPLATE_TEMPLATES9, typename T9
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES11	IUTEST_FUNCTION_TEMPLATE_TEMPLATES10, typename T10
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES12	IUTEST_FUNCTION_TEMPLATE_TEMPLATES11, typename T11
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES13	IUTEST_FUNCTION_TEMPLATE_TEMPLATES12, typename T12
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES14	IUTEST_FUNCTION_TEMPLATE_TEMPLATES13, typename T13
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES15	IUTEST_FUNCTION_TEMPLATE_TEMPLATES14, typename T14
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES16	IUTEST_FUNCTION_TEMPLATE_TEMPLATES15, typename T15
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES17	IUTEST_FUNCTION_TEMPLATE_TEMPLATES16, typename T16
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES18	IUTEST_FUNCTION_TEMPLATE_TEMPLATES17, typename T17
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES19	IUTEST_FUNCTION_TEMPLATE_TEMPLATES18, typename T18
#define IUTEST_FUNCTION_TEMPLATE_TEMPLATES20	IUTEST_FUNCTION_TEMPLATE_TEMPLATES19, typename T19

#define IUTEST_FUNCTION_TEMPLATE_ARGS1		T0
#define IUTEST_FUNCTION_TEMPLATE_ARGS2		IUTEST_FUNCTION_TEMPLATE_ARGS1, T1
#define IUTEST_FUNCTION_TEMPLATE_ARGS3		IUTEST_FUNCTION_TEMPLATE_ARGS2, T2
#define IUTEST_FUNCTION_TEMPLATE_ARGS4		IUTEST_FUNCTION_TEMPLATE_ARGS3, T3
#define IUTEST_FUNCTION_TEMPLATE_ARGS5		IUTEST_FUNCTION_TEMPLATE_ARGS4, T4
#define IUTEST_FUNCTION_TEMPLATE_ARGS6		IUTEST_FUNCTION_TEMPLATE_ARGS5, T5
#define IUTEST_FUNCTION_TEMPLATE_ARGS7		IUTEST_FUNCTION_TEMPLATE_ARGS6, T6
#define IUTEST_FUNCTION_TEMPLATE_ARGS8		IUTEST_FUNCTION_TEMPLATE_ARGS7, T7
#define IUTEST_FUNCTION_TEMPLATE_ARGS9		IUTEST_FUNCTION_TEMPLATE_ARGS8, T8
#define IUTEST_FUNCTION_TEMPLATE_ARGS10		IUTEST_FUNCTION_TEMPLATE_ARGS9, T9
#define IUTEST_FUNCTION_TEMPLATE_ARGS11		IUTEST_FUNCTION_TEMPLATE_ARGS10, T10
#define IUTEST_FUNCTION_TEMPLATE_ARGS12		IUTEST_FUNCTION_TEMPLATE_ARGS11, T11
#define IUTEST_FUNCTION_TEMPLATE_ARGS13		IUTEST_FUNCTION_TEMPLATE_ARGS12, T12
#define IUTEST_FUNCTION_TEMPLATE_ARGS14		IUTEST_FUNCTION_TEMPLATE_ARGS13, T13
#define IUTEST_FUNCTION_TEMPLATE_ARGS15		IUTEST_FUNCTION_TEMPLATE_ARGS14, T14
#define IUTEST_FUNCTION_TEMPLATE_ARGS16		IUTEST_FUNCTION_TEMPLATE_ARGS15, T15
#define IUTEST_FUNCTION_TEMPLATE_ARGS17		IUTEST_FUNCTION_TEMPLATE_ARGS16, T16
#define IUTEST_FUNCTION_TEMPLATE_ARGS18		IUTEST_FUNCTION_TEMPLATE_ARGS17, T17
#define IUTEST_FUNCTION_TEMPLATE_ARGS19		IUTEST_FUNCTION_TEMPLATE_ARGS18, T18
#define IUTEST_FUNCTION_TEMPLATE_ARGS20		IUTEST_FUNCTION_TEMPLATE_ARGS19, T19

#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS1		T0 t0
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS2		IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS1, T1 t1
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS3		IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS2, T2 t2
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS4		IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS3, T3 t3
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS5		IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS4, T4 t4
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS6		IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS5, T5 t5
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS7		IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS6, T6 t6
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS8		IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS7, T7 t7
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS9		IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS8, T8 t8
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS10	IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS9, T9 t9
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS11	IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS10, T10 t10
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS12	IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS11, T11 t11
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS13	IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS12, T12 t12
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS14	IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS13, T13 t13
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS15	IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS14, T14 t14
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS16	IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS15, T15 t15
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS17	IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS16, T16 t16
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS18	IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS17, T17 t17
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS19	IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS18, T18 t18
#define IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS20	IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS19, T19 t19

#define IUTEST_FUNCTION_TEMPLATE_VALUES1		t0
#define IUTEST_FUNCTION_TEMPLATE_VALUES2		IUTEST_FUNCTION_TEMPLATE_VALUES1, t1
#define IUTEST_FUNCTION_TEMPLATE_VALUES3		IUTEST_FUNCTION_TEMPLATE_VALUES2, t2
#define IUTEST_FUNCTION_TEMPLATE_VALUES4		IUTEST_FUNCTION_TEMPLATE_VALUES3, t3
#define IUTEST_FUNCTION_TEMPLATE_VALUES5		IUTEST_FUNCTION_TEMPLATE_VALUES4, t4
#define IUTEST_FUNCTION_TEMPLATE_VALUES6		IUTEST_FUNCTION_TEMPLATE_VALUES5, t5
#define IUTEST_FUNCTION_TEMPLATE_VALUES7		IUTEST_FUNCTION_TEMPLATE_VALUES6, t6
#define IUTEST_FUNCTION_TEMPLATE_VALUES8		IUTEST_FUNCTION_TEMPLATE_VALUES7, t7
#define IUTEST_FUNCTION_TEMPLATE_VALUES9		IUTEST_FUNCTION_TEMPLATE_VALUES8, t8
#define IUTEST_FUNCTION_TEMPLATE_VALUES10		IUTEST_FUNCTION_TEMPLATE_VALUES9, t9
#define IUTEST_FUNCTION_TEMPLATE_VALUES11		IUTEST_FUNCTION_TEMPLATE_VALUES10, t10
#define IUTEST_FUNCTION_TEMPLATE_VALUES12		IUTEST_FUNCTION_TEMPLATE_VALUES11, t11
#define IUTEST_FUNCTION_TEMPLATE_VALUES13		IUTEST_FUNCTION_TEMPLATE_VALUES12, t12
#define IUTEST_FUNCTION_TEMPLATE_VALUES14		IUTEST_FUNCTION_TEMPLATE_VALUES13, t13
#define IUTEST_FUNCTION_TEMPLATE_VALUES15		IUTEST_FUNCTION_TEMPLATE_VALUES14, t14
#define IUTEST_FUNCTION_TEMPLATE_VALUES16		IUTEST_FUNCTION_TEMPLATE_VALUES15, t15
#define IUTEST_FUNCTION_TEMPLATE_VALUES17		IUTEST_FUNCTION_TEMPLATE_VALUES16, t16
#define IUTEST_FUNCTION_TEMPLATE_VALUES18		IUTEST_FUNCTION_TEMPLATE_VALUES17, t17
#define IUTEST_FUNCTION_TEMPLATE_VALUES19		IUTEST_FUNCTION_TEMPLATE_VALUES18, t18
#define IUTEST_FUNCTION_TEMPLATE_VALUES20		IUTEST_FUNCTION_TEMPLATE_VALUES19, t19

#ifdef INCG_IRIS_iutest_function_traits_undef_HPP_
#  undef INCG_IRIS_iutest_function_traits_undef_HPP_
#endif

#endif
