//======================================================================
//-----------------------------------------------------------------------
/**
 * @file		iutest_template_util_defs.hpp
 * @brief		iris unit test template ヘルパー定義 ファイル
 *
 * @author		t.sirayanagi
 * @version		1.0
 *
 * @par			copyright
 * Copyright (C) 2012, Takazumi Shirayanagi\n
 * The new BSD License is applied to this software.
 * see LICENSE
*/
//-----------------------------------------------------------------------
//======================================================================
#ifndef INCG_IRIS_iutest_template_util_defs_HPP_
#define INCG_IRIS_iutest_template_util_defs_HPP_

//======================================================================
// include
#include "iutest_pp.hpp"

//======================================================================
// define
#define IUTEST_TEMPLATE_UTIL_TEMPLATES(n, x)		IUTEST_PP_CAT(IUTEST_TEMPLATE_UTIL_TEMPLATES, n)(x)
#define IUTEST_TEMPLATE_UTIL_TEMPLATES_TYPENAME(n)	IUTEST_PP_CAT(IUTEST_TEMPLATE_UTIL_TEMPLATES, n)(typename)

#define IUTEST_TEMPLATE_UTIL_TEMPLATES1(x)		x T0
#define IUTEST_TEMPLATE_UTIL_TEMPLATES2(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES1(x), x T1
#define IUTEST_TEMPLATE_UTIL_TEMPLATES3(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES2(x), x T2
#define IUTEST_TEMPLATE_UTIL_TEMPLATES4(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES3(x), x T3
#define IUTEST_TEMPLATE_UTIL_TEMPLATES5(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES4(x), x T4
#define IUTEST_TEMPLATE_UTIL_TEMPLATES6(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES5(x), x T5
#define IUTEST_TEMPLATE_UTIL_TEMPLATES7(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES6(x), x T6
#define IUTEST_TEMPLATE_UTIL_TEMPLATES8(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES7(x), x T7
#define IUTEST_TEMPLATE_UTIL_TEMPLATES9(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES8(x), x T8
#define IUTEST_TEMPLATE_UTIL_TEMPLATES10(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES9(x), x T9
#define IUTEST_TEMPLATE_UTIL_TEMPLATES11(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES10(x), x T10
#define IUTEST_TEMPLATE_UTIL_TEMPLATES12(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES11(x), x T11
#define IUTEST_TEMPLATE_UTIL_TEMPLATES13(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES12(x), x T12
#define IUTEST_TEMPLATE_UTIL_TEMPLATES14(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES13(x), x T13
#define IUTEST_TEMPLATE_UTIL_TEMPLATES15(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES14(x), x T14
#define IUTEST_TEMPLATE_UTIL_TEMPLATES16(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES15(x), x T15
#define IUTEST_TEMPLATE_UTIL_TEMPLATES17(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES16(x), x T16
#define IUTEST_TEMPLATE_UTIL_TEMPLATES18(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES17(x), x T17
#define IUTEST_TEMPLATE_UTIL_TEMPLATES19(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES18(x), x T18
#define IUTEST_TEMPLATE_UTIL_TEMPLATES20(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES19(x), x T19
#define IUTEST_TEMPLATE_UTIL_TEMPLATES21(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES20(x), x T20
#define IUTEST_TEMPLATE_UTIL_TEMPLATES22(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES21(x), x T21
#define IUTEST_TEMPLATE_UTIL_TEMPLATES23(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES22(x), x T22
#define IUTEST_TEMPLATE_UTIL_TEMPLATES24(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES23(x), x T23
#define IUTEST_TEMPLATE_UTIL_TEMPLATES25(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES24(x), x T24
#define IUTEST_TEMPLATE_UTIL_TEMPLATES26(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES25(x), x T25
#define IUTEST_TEMPLATE_UTIL_TEMPLATES27(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES26(x), x T26
#define IUTEST_TEMPLATE_UTIL_TEMPLATES28(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES27(x), x T27
#define IUTEST_TEMPLATE_UTIL_TEMPLATES29(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES28(x), x T28
#define IUTEST_TEMPLATE_UTIL_TEMPLATES30(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES29(x), x T29
#define IUTEST_TEMPLATE_UTIL_TEMPLATES31(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES30(x), x T30
#define IUTEST_TEMPLATE_UTIL_TEMPLATES32(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES31(x), x T31
#define IUTEST_TEMPLATE_UTIL_TEMPLATES33(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES32(x), x T32
#define IUTEST_TEMPLATE_UTIL_TEMPLATES34(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES33(x), x T33
#define IUTEST_TEMPLATE_UTIL_TEMPLATES35(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES34(x), x T34
#define IUTEST_TEMPLATE_UTIL_TEMPLATES36(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES35(x), x T35
#define IUTEST_TEMPLATE_UTIL_TEMPLATES37(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES36(x), x T36
#define IUTEST_TEMPLATE_UTIL_TEMPLATES38(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES37(x), x T37
#define IUTEST_TEMPLATE_UTIL_TEMPLATES39(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES38(x), x T38
#define IUTEST_TEMPLATE_UTIL_TEMPLATES40(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES39(x), x T39
#define IUTEST_TEMPLATE_UTIL_TEMPLATES41(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES40(x), x T40
#define IUTEST_TEMPLATE_UTIL_TEMPLATES42(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES41(x), x T41
#define IUTEST_TEMPLATE_UTIL_TEMPLATES43(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES42(x), x T42
#define IUTEST_TEMPLATE_UTIL_TEMPLATES44(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES43(x), x T43
#define IUTEST_TEMPLATE_UTIL_TEMPLATES45(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES44(x), x T44
#define IUTEST_TEMPLATE_UTIL_TEMPLATES46(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES45(x), x T45
#define IUTEST_TEMPLATE_UTIL_TEMPLATES47(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES46(x), x T46
#define IUTEST_TEMPLATE_UTIL_TEMPLATES48(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES47(x), x T47
#define IUTEST_TEMPLATE_UTIL_TEMPLATES49(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES48(x), x T48
#define IUTEST_TEMPLATE_UTIL_TEMPLATES50(x)		IUTEST_TEMPLATE_UTIL_TEMPLATES49(x), x T49

#define IUTEST_TEMPLATE_UTIL_ARGS(n)			IUTEST_PP_CAT(IUTEST_TEMPLATE_UTIL_ARGS, n)
#define IUTEST_TEMPLATE_UTIL_ARGS1				T0
#define IUTEST_TEMPLATE_UTIL_ARGS2				IUTEST_TEMPLATE_UTIL_ARGS1, T1
#define IUTEST_TEMPLATE_UTIL_ARGS3				IUTEST_TEMPLATE_UTIL_ARGS2, T2
#define IUTEST_TEMPLATE_UTIL_ARGS4				IUTEST_TEMPLATE_UTIL_ARGS3, T3
#define IUTEST_TEMPLATE_UTIL_ARGS5				IUTEST_TEMPLATE_UTIL_ARGS4, T4
#define IUTEST_TEMPLATE_UTIL_ARGS6				IUTEST_TEMPLATE_UTIL_ARGS5, T5
#define IUTEST_TEMPLATE_UTIL_ARGS7				IUTEST_TEMPLATE_UTIL_ARGS6, T6
#define IUTEST_TEMPLATE_UTIL_ARGS8				IUTEST_TEMPLATE_UTIL_ARGS7, T7
#define IUTEST_TEMPLATE_UTIL_ARGS9				IUTEST_TEMPLATE_UTIL_ARGS8, T8
#define IUTEST_TEMPLATE_UTIL_ARGS10				IUTEST_TEMPLATE_UTIL_ARGS9, T9
#define IUTEST_TEMPLATE_UTIL_ARGS11				IUTEST_TEMPLATE_UTIL_ARGS10, T10
#define IUTEST_TEMPLATE_UTIL_ARGS12				IUTEST_TEMPLATE_UTIL_ARGS11, T11
#define IUTEST_TEMPLATE_UTIL_ARGS13				IUTEST_TEMPLATE_UTIL_ARGS12, T12
#define IUTEST_TEMPLATE_UTIL_ARGS14				IUTEST_TEMPLATE_UTIL_ARGS13, T13
#define IUTEST_TEMPLATE_UTIL_ARGS15				IUTEST_TEMPLATE_UTIL_ARGS14, T14
#define IUTEST_TEMPLATE_UTIL_ARGS16				IUTEST_TEMPLATE_UTIL_ARGS15, T15
#define IUTEST_TEMPLATE_UTIL_ARGS17				IUTEST_TEMPLATE_UTIL_ARGS16, T16
#define IUTEST_TEMPLATE_UTIL_ARGS18				IUTEST_TEMPLATE_UTIL_ARGS17, T17
#define IUTEST_TEMPLATE_UTIL_ARGS19				IUTEST_TEMPLATE_UTIL_ARGS18, T18
#define IUTEST_TEMPLATE_UTIL_ARGS20				IUTEST_TEMPLATE_UTIL_ARGS19, T19
#define IUTEST_TEMPLATE_UTIL_ARGS21				IUTEST_TEMPLATE_UTIL_ARGS20, T20
#define IUTEST_TEMPLATE_UTIL_ARGS22				IUTEST_TEMPLATE_UTIL_ARGS21, T21
#define IUTEST_TEMPLATE_UTIL_ARGS23				IUTEST_TEMPLATE_UTIL_ARGS22, T22
#define IUTEST_TEMPLATE_UTIL_ARGS24				IUTEST_TEMPLATE_UTIL_ARGS23, T23
#define IUTEST_TEMPLATE_UTIL_ARGS25				IUTEST_TEMPLATE_UTIL_ARGS24, T24
#define IUTEST_TEMPLATE_UTIL_ARGS26				IUTEST_TEMPLATE_UTIL_ARGS25, T25
#define IUTEST_TEMPLATE_UTIL_ARGS27				IUTEST_TEMPLATE_UTIL_ARGS26, T26
#define IUTEST_TEMPLATE_UTIL_ARGS28				IUTEST_TEMPLATE_UTIL_ARGS27, T27
#define IUTEST_TEMPLATE_UTIL_ARGS29				IUTEST_TEMPLATE_UTIL_ARGS28, T28
#define IUTEST_TEMPLATE_UTIL_ARGS30				IUTEST_TEMPLATE_UTIL_ARGS29, T29
#define IUTEST_TEMPLATE_UTIL_ARGS31				IUTEST_TEMPLATE_UTIL_ARGS30, T30
#define IUTEST_TEMPLATE_UTIL_ARGS32				IUTEST_TEMPLATE_UTIL_ARGS31, T31
#define IUTEST_TEMPLATE_UTIL_ARGS33				IUTEST_TEMPLATE_UTIL_ARGS32, T32
#define IUTEST_TEMPLATE_UTIL_ARGS34				IUTEST_TEMPLATE_UTIL_ARGS33, T33
#define IUTEST_TEMPLATE_UTIL_ARGS35				IUTEST_TEMPLATE_UTIL_ARGS34, T34
#define IUTEST_TEMPLATE_UTIL_ARGS36				IUTEST_TEMPLATE_UTIL_ARGS35, T35
#define IUTEST_TEMPLATE_UTIL_ARGS37				IUTEST_TEMPLATE_UTIL_ARGS36, T36
#define IUTEST_TEMPLATE_UTIL_ARGS38				IUTEST_TEMPLATE_UTIL_ARGS37, T37
#define IUTEST_TEMPLATE_UTIL_ARGS39				IUTEST_TEMPLATE_UTIL_ARGS38, T38
#define IUTEST_TEMPLATE_UTIL_ARGS40				IUTEST_TEMPLATE_UTIL_ARGS39, T39
#define IUTEST_TEMPLATE_UTIL_ARGS41				IUTEST_TEMPLATE_UTIL_ARGS40, T40
#define IUTEST_TEMPLATE_UTIL_ARGS42				IUTEST_TEMPLATE_UTIL_ARGS41, T41
#define IUTEST_TEMPLATE_UTIL_ARGS43				IUTEST_TEMPLATE_UTIL_ARGS42, T42
#define IUTEST_TEMPLATE_UTIL_ARGS44				IUTEST_TEMPLATE_UTIL_ARGS43, T43
#define IUTEST_TEMPLATE_UTIL_ARGS45				IUTEST_TEMPLATE_UTIL_ARGS44, T44
#define IUTEST_TEMPLATE_UTIL_ARGS46				IUTEST_TEMPLATE_UTIL_ARGS45, T45
#define IUTEST_TEMPLATE_UTIL_ARGS47				IUTEST_TEMPLATE_UTIL_ARGS46, T46
#define IUTEST_TEMPLATE_UTIL_ARGS48				IUTEST_TEMPLATE_UTIL_ARGS47, T47
#define IUTEST_TEMPLATE_UTIL_ARGS49				IUTEST_TEMPLATE_UTIL_ARGS48, T48
#define IUTEST_TEMPLATE_UTIL_ARGS50				IUTEST_TEMPLATE_UTIL_ARGS49, T49

#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS(n)	IUTEST_PP_CAT(IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS, n)
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS1		T0 t0
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS2		IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS1, T1 t1
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS3		IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS2, T2 t2
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS4		IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS3, T3 t3
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS5		IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS4, T4 t4
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS6		IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS5, T5 t5
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS7		IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS6, T6 t6
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS8		IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS7, T7 t7
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS9		IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS8, T8 t8
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS10	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS9, T9 t9
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS11	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS10, T10 t10
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS12	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS11, T11 t11
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS13	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS12, T12 t12
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS14	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS13, T13 t13
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS15	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS14, T14 t14
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS16	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS15, T15 t15
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS17	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS16, T16 t16
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS18	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS17, T17 t17
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS19	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS18, T18 t18
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS20	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS19, T19 t19
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS21	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS20, T20 t20
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS22	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS21, T21 t21
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS23	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS22, T22 t22
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS24	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS23, T23 t23
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS25	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS24, T24 t24
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS26	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS25, T25 t25
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS27	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS26, T26 t26
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS28	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS27, T27 t27
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS29	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS28, T28 t28
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS30	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS29, T29 t29
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS31	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS30, T30 t30
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS32	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS31, T31 t31
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS33	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS32, T32 t32
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS34	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS33, T33 t33
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS35	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS34, T34 t34
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS36	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS35, T35 t35
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS37	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS36, T36 t36
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS38	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS37, T37 t37
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS39	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS38, T38 t38
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS40	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS39, T39 t39
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS41	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS40, T40 t40
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS42	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS41, T41 t41
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS43	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS42, T42 t42
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS44	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS43, T43 t43
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS45	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS44, T44 t44
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS46	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS45, T45 t45
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS47	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS46, T46 t46
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS48	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS47, T47 t47
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS49	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS48, T48 t48
#define IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS50	IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS49, T49 t49

#define IUTEST_TEMPLATE_UTIL_VALUES(n)			IUTEST_PP_CAT(IUTEST_TEMPLATE_UTIL_VALUES, n)
#define IUTEST_TEMPLATE_UTIL_VALUES1			t0
#define IUTEST_TEMPLATE_UTIL_VALUES2			IUTEST_TEMPLATE_UTIL_VALUES1, t1
#define IUTEST_TEMPLATE_UTIL_VALUES3			IUTEST_TEMPLATE_UTIL_VALUES2, t2
#define IUTEST_TEMPLATE_UTIL_VALUES4			IUTEST_TEMPLATE_UTIL_VALUES3, t3
#define IUTEST_TEMPLATE_UTIL_VALUES5			IUTEST_TEMPLATE_UTIL_VALUES4, t4
#define IUTEST_TEMPLATE_UTIL_VALUES6			IUTEST_TEMPLATE_UTIL_VALUES5, t5
#define IUTEST_TEMPLATE_UTIL_VALUES7			IUTEST_TEMPLATE_UTIL_VALUES6, t6
#define IUTEST_TEMPLATE_UTIL_VALUES8			IUTEST_TEMPLATE_UTIL_VALUES7, t7
#define IUTEST_TEMPLATE_UTIL_VALUES9			IUTEST_TEMPLATE_UTIL_VALUES8, t8
#define IUTEST_TEMPLATE_UTIL_VALUES10			IUTEST_TEMPLATE_UTIL_VALUES9, t9
#define IUTEST_TEMPLATE_UTIL_VALUES11			IUTEST_TEMPLATE_UTIL_VALUES10, t10
#define IUTEST_TEMPLATE_UTIL_VALUES12			IUTEST_TEMPLATE_UTIL_VALUES11, t11
#define IUTEST_TEMPLATE_UTIL_VALUES13			IUTEST_TEMPLATE_UTIL_VALUES12, t12
#define IUTEST_TEMPLATE_UTIL_VALUES14			IUTEST_TEMPLATE_UTIL_VALUES13, t13
#define IUTEST_TEMPLATE_UTIL_VALUES15			IUTEST_TEMPLATE_UTIL_VALUES14, t14
#define IUTEST_TEMPLATE_UTIL_VALUES16			IUTEST_TEMPLATE_UTIL_VALUES15, t15
#define IUTEST_TEMPLATE_UTIL_VALUES17			IUTEST_TEMPLATE_UTIL_VALUES16, t16
#define IUTEST_TEMPLATE_UTIL_VALUES18			IUTEST_TEMPLATE_UTIL_VALUES17, t17
#define IUTEST_TEMPLATE_UTIL_VALUES19			IUTEST_TEMPLATE_UTIL_VALUES18, t18
#define IUTEST_TEMPLATE_UTIL_VALUES20			IUTEST_TEMPLATE_UTIL_VALUES19, t19
#define IUTEST_TEMPLATE_UTIL_VALUES21			IUTEST_TEMPLATE_UTIL_VALUES20, t20
#define IUTEST_TEMPLATE_UTIL_VALUES22			IUTEST_TEMPLATE_UTIL_VALUES21, t21
#define IUTEST_TEMPLATE_UTIL_VALUES23			IUTEST_TEMPLATE_UTIL_VALUES22, t22
#define IUTEST_TEMPLATE_UTIL_VALUES24			IUTEST_TEMPLATE_UTIL_VALUES23, t23
#define IUTEST_TEMPLATE_UTIL_VALUES25			IUTEST_TEMPLATE_UTIL_VALUES24, t24
#define IUTEST_TEMPLATE_UTIL_VALUES26			IUTEST_TEMPLATE_UTIL_VALUES25, t25
#define IUTEST_TEMPLATE_UTIL_VALUES27			IUTEST_TEMPLATE_UTIL_VALUES26, t26
#define IUTEST_TEMPLATE_UTIL_VALUES28			IUTEST_TEMPLATE_UTIL_VALUES27, t27
#define IUTEST_TEMPLATE_UTIL_VALUES29			IUTEST_TEMPLATE_UTIL_VALUES28, t28
#define IUTEST_TEMPLATE_UTIL_VALUES30			IUTEST_TEMPLATE_UTIL_VALUES29, t29
#define IUTEST_TEMPLATE_UTIL_VALUES31			IUTEST_TEMPLATE_UTIL_VALUES30, t30
#define IUTEST_TEMPLATE_UTIL_VALUES32			IUTEST_TEMPLATE_UTIL_VALUES31, t31
#define IUTEST_TEMPLATE_UTIL_VALUES33			IUTEST_TEMPLATE_UTIL_VALUES32, t32
#define IUTEST_TEMPLATE_UTIL_VALUES34			IUTEST_TEMPLATE_UTIL_VALUES33, t33
#define IUTEST_TEMPLATE_UTIL_VALUES35			IUTEST_TEMPLATE_UTIL_VALUES34, t34
#define IUTEST_TEMPLATE_UTIL_VALUES36			IUTEST_TEMPLATE_UTIL_VALUES35, t35
#define IUTEST_TEMPLATE_UTIL_VALUES37			IUTEST_TEMPLATE_UTIL_VALUES36, t36
#define IUTEST_TEMPLATE_UTIL_VALUES38			IUTEST_TEMPLATE_UTIL_VALUES37, t37
#define IUTEST_TEMPLATE_UTIL_VALUES39			IUTEST_TEMPLATE_UTIL_VALUES38, t38
#define IUTEST_TEMPLATE_UTIL_VALUES40			IUTEST_TEMPLATE_UTIL_VALUES39, t39
#define IUTEST_TEMPLATE_UTIL_VALUES41			IUTEST_TEMPLATE_UTIL_VALUES40, t40
#define IUTEST_TEMPLATE_UTIL_VALUES42			IUTEST_TEMPLATE_UTIL_VALUES41, t41
#define IUTEST_TEMPLATE_UTIL_VALUES43			IUTEST_TEMPLATE_UTIL_VALUES42, t42
#define IUTEST_TEMPLATE_UTIL_VALUES44			IUTEST_TEMPLATE_UTIL_VALUES43, t43
#define IUTEST_TEMPLATE_UTIL_VALUES45			IUTEST_TEMPLATE_UTIL_VALUES44, t44
#define IUTEST_TEMPLATE_UTIL_VALUES46			IUTEST_TEMPLATE_UTIL_VALUES45, t45
#define IUTEST_TEMPLATE_UTIL_VALUES47			IUTEST_TEMPLATE_UTIL_VALUES46, t46
#define IUTEST_TEMPLATE_UTIL_VALUES48			IUTEST_TEMPLATE_UTIL_VALUES47, t47
#define IUTEST_TEMPLATE_UTIL_VALUES49			IUTEST_TEMPLATE_UTIL_VALUES48, t48
#define IUTEST_TEMPLATE_UTIL_VALUES50			IUTEST_TEMPLATE_UTIL_VALUES49, t49

#ifdef INCG_IRIS_iutest_template_util_undef_HPP_
#  undef INCG_IRIS_iutest_template_util_undef_HPP_
#endif

#endif
