//======================================================================
//-----------------------------------------------------------------------
/**
 * @file		iutest_template_util_undef.hpp
 * @brief		iris unit test template ヘルパー define undef ファイル
 *
 * @author		t.sirayanagi
 * @version		1.0
 *
 * @par			copyright
 * Copyright (C) 2012, Takazumi Shirayanagi\n
 * The new BSD License is applied to this software.
 * see LICENSE
*/
//-----------------------------------------------------------------------
//======================================================================
#ifndef INCG_IRIS_iutest_template_util_undef_HPP_
#define INCG_IRIS_iutest_template_util_undef_HPP_

//======================================================================
// define

#undef IUTEST_TEMPLATE_UTIL_TEMPLATES
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES_TYPENAME
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES1
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES2
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES3
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES4
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES5
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES6
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES7
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES8
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES9
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES10
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES11
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES12
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES13
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES14
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES15
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES16
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES17
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES18
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES19
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES20
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES21
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES22
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES23
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES24
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES25
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES26
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES27
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES28
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES29
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES30
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES31
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES32
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES33
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES34
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES35
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES36
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES37
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES38
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES39
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES40
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES41
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES42
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES43
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES44
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES45
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES46
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES47
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES48
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES49
#undef IUTEST_TEMPLATE_UTIL_TEMPLATES50

#undef IUTEST_TEMPLATE_UTIL_ARGS
#undef IUTEST_TEMPLATE_UTIL_ARGS1
#undef IUTEST_TEMPLATE_UTIL_ARGS2
#undef IUTEST_TEMPLATE_UTIL_ARGS3
#undef IUTEST_TEMPLATE_UTIL_ARGS4
#undef IUTEST_TEMPLATE_UTIL_ARGS5
#undef IUTEST_TEMPLATE_UTIL_ARGS6
#undef IUTEST_TEMPLATE_UTIL_ARGS7
#undef IUTEST_TEMPLATE_UTIL_ARGS8
#undef IUTEST_TEMPLATE_UTIL_ARGS9
#undef IUTEST_TEMPLATE_UTIL_ARGS10
#undef IUTEST_TEMPLATE_UTIL_ARGS11
#undef IUTEST_TEMPLATE_UTIL_ARGS12
#undef IUTEST_TEMPLATE_UTIL_ARGS13
#undef IUTEST_TEMPLATE_UTIL_ARGS14
#undef IUTEST_TEMPLATE_UTIL_ARGS15
#undef IUTEST_TEMPLATE_UTIL_ARGS16
#undef IUTEST_TEMPLATE_UTIL_ARGS17
#undef IUTEST_TEMPLATE_UTIL_ARGS18
#undef IUTEST_TEMPLATE_UTIL_ARGS19
#undef IUTEST_TEMPLATE_UTIL_ARGS20
#undef IUTEST_TEMPLATE_UTIL_ARGS21
#undef IUTEST_TEMPLATE_UTIL_ARGS22
#undef IUTEST_TEMPLATE_UTIL_ARGS23
#undef IUTEST_TEMPLATE_UTIL_ARGS24
#undef IUTEST_TEMPLATE_UTIL_ARGS25
#undef IUTEST_TEMPLATE_UTIL_ARGS26
#undef IUTEST_TEMPLATE_UTIL_ARGS27
#undef IUTEST_TEMPLATE_UTIL_ARGS28
#undef IUTEST_TEMPLATE_UTIL_ARGS29
#undef IUTEST_TEMPLATE_UTIL_ARGS30
#undef IUTEST_TEMPLATE_UTIL_ARGS31
#undef IUTEST_TEMPLATE_UTIL_ARGS32
#undef IUTEST_TEMPLATE_UTIL_ARGS33
#undef IUTEST_TEMPLATE_UTIL_ARGS34
#undef IUTEST_TEMPLATE_UTIL_ARGS35
#undef IUTEST_TEMPLATE_UTIL_ARGS36
#undef IUTEST_TEMPLATE_UTIL_ARGS37
#undef IUTEST_TEMPLATE_UTIL_ARGS38
#undef IUTEST_TEMPLATE_UTIL_ARGS39
#undef IUTEST_TEMPLATE_UTIL_ARGS40
#undef IUTEST_TEMPLATE_UTIL_ARGS41
#undef IUTEST_TEMPLATE_UTIL_ARGS42
#undef IUTEST_TEMPLATE_UTIL_ARGS43
#undef IUTEST_TEMPLATE_UTIL_ARGS44
#undef IUTEST_TEMPLATE_UTIL_ARGS45
#undef IUTEST_TEMPLATE_UTIL_ARGS46
#undef IUTEST_TEMPLATE_UTIL_ARGS47
#undef IUTEST_TEMPLATE_UTIL_ARGS48
#undef IUTEST_TEMPLATE_UTIL_ARGS49
#undef IUTEST_TEMPLATE_UTIL_ARGS50

#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS1
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS2
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS3
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS4
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS5
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS6
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS7
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS8
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS9
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS10
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS11
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS12
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS13
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS14
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS15
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS16
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS17
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS18
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS19
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS20
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS21
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS22
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS23
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS24
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS25
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS26
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS27
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS28
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS29
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS30
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS31
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS32
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS33
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS34
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS35
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS36
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS37
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS38
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS39
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS40
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS41
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS42
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS43
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS44
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS45
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS46
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS47
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS48
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS49
#undef IUTEST_TEMPLATE_UTIL_FUNCTION_ARGS50

#undef IUTEST_TEMPLATE_UTIL_VALUES
#undef IUTEST_TEMPLATE_UTIL_VALUES1
#undef IUTEST_TEMPLATE_UTIL_VALUES2
#undef IUTEST_TEMPLATE_UTIL_VALUES3
#undef IUTEST_TEMPLATE_UTIL_VALUES4
#undef IUTEST_TEMPLATE_UTIL_VALUES5
#undef IUTEST_TEMPLATE_UTIL_VALUES6
#undef IUTEST_TEMPLATE_UTIL_VALUES7
#undef IUTEST_TEMPLATE_UTIL_VALUES8
#undef IUTEST_TEMPLATE_UTIL_VALUES9
#undef IUTEST_TEMPLATE_UTIL_VALUES10
#undef IUTEST_TEMPLATE_UTIL_VALUES11
#undef IUTEST_TEMPLATE_UTIL_VALUES12
#undef IUTEST_TEMPLATE_UTIL_VALUES13
#undef IUTEST_TEMPLATE_UTIL_VALUES14
#undef IUTEST_TEMPLATE_UTIL_VALUES15
#undef IUTEST_TEMPLATE_UTIL_VALUES16
#undef IUTEST_TEMPLATE_UTIL_VALUES17
#undef IUTEST_TEMPLATE_UTIL_VALUES18
#undef IUTEST_TEMPLATE_UTIL_VALUES19
#undef IUTEST_TEMPLATE_UTIL_VALUES20
#undef IUTEST_TEMPLATE_UTIL_VALUES21
#undef IUTEST_TEMPLATE_UTIL_VALUES22
#undef IUTEST_TEMPLATE_UTIL_VALUES23
#undef IUTEST_TEMPLATE_UTIL_VALUES24
#undef IUTEST_TEMPLATE_UTIL_VALUES25
#undef IUTEST_TEMPLATE_UTIL_VALUES26
#undef IUTEST_TEMPLATE_UTIL_VALUES27
#undef IUTEST_TEMPLATE_UTIL_VALUES28
#undef IUTEST_TEMPLATE_UTIL_VALUES29
#undef IUTEST_TEMPLATE_UTIL_VALUES30
#undef IUTEST_TEMPLATE_UTIL_VALUES31
#undef IUTEST_TEMPLATE_UTIL_VALUES32
#undef IUTEST_TEMPLATE_UTIL_VALUES33
#undef IUTEST_TEMPLATE_UTIL_VALUES34
#undef IUTEST_TEMPLATE_UTIL_VALUES35
#undef IUTEST_TEMPLATE_UTIL_VALUES36
#undef IUTEST_TEMPLATE_UTIL_VALUES37
#undef IUTEST_TEMPLATE_UTIL_VALUES38
#undef IUTEST_TEMPLATE_UTIL_VALUES39
#undef IUTEST_TEMPLATE_UTIL_VALUES40
#undef IUTEST_TEMPLATE_UTIL_VALUES41
#undef IUTEST_TEMPLATE_UTIL_VALUES42
#undef IUTEST_TEMPLATE_UTIL_VALUES43
#undef IUTEST_TEMPLATE_UTIL_VALUES44
#undef IUTEST_TEMPLATE_UTIL_VALUES45
#undef IUTEST_TEMPLATE_UTIL_VALUES46
#undef IUTEST_TEMPLATE_UTIL_VALUES47
#undef IUTEST_TEMPLATE_UTIL_VALUES48
#undef IUTEST_TEMPLATE_UTIL_VALUES49
#undef IUTEST_TEMPLATE_UTIL_VALUES50

#ifdef INCG_IRIS_iutest_template_util_defs_HPP_
#  undef INCG_IRIS_iutest_template_util_defs_HPP_
#endif

#endif
