//======================================================================
//-----------------------------------------------------------------------
/**
 * @file		iutest_function_traits_undef.h
 * @brief		iris unit test function traits ヘルパー define undef ファイル
 *
 * @author		t.sirayanagi
 * @version		1.0
 *
 * @par			copyright
 * Copyright (C) 2012, Takazumi Shirayanagi\n
 * The new BSD License is applied to this software.
 * see LICENSE
*/
//-----------------------------------------------------------------------
//======================================================================
#ifndef INCG_IRIS_iutest_function_traits_undef_H_
#define INCG_IRIS_iutest_function_traits_undef_H_

//======================================================================
// define

#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES1
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES2
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES3
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES4
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES5
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES6
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES7
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES8
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES9
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES10
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES11
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES12
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES13
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES14
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES15
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES16
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES17
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES18
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES19
#undef IUTEST_FUNCTION_TEMPLATE_TEMPLATES20

#undef IUTEST_FUNCTION_TEMPLATE_ARGS1
#undef IUTEST_FUNCTION_TEMPLATE_ARGS2
#undef IUTEST_FUNCTION_TEMPLATE_ARGS3
#undef IUTEST_FUNCTION_TEMPLATE_ARGS4
#undef IUTEST_FUNCTION_TEMPLATE_ARGS5
#undef IUTEST_FUNCTION_TEMPLATE_ARGS6
#undef IUTEST_FUNCTION_TEMPLATE_ARGS7
#undef IUTEST_FUNCTION_TEMPLATE_ARGS8
#undef IUTEST_FUNCTION_TEMPLATE_ARGS9
#undef IUTEST_FUNCTION_TEMPLATE_ARGS10
#undef IUTEST_FUNCTION_TEMPLATE_ARGS11
#undef IUTEST_FUNCTION_TEMPLATE_ARGS12
#undef IUTEST_FUNCTION_TEMPLATE_ARGS13
#undef IUTEST_FUNCTION_TEMPLATE_ARGS14
#undef IUTEST_FUNCTION_TEMPLATE_ARGS15
#undef IUTEST_FUNCTION_TEMPLATE_ARGS16
#undef IUTEST_FUNCTION_TEMPLATE_ARGS17
#undef IUTEST_FUNCTION_TEMPLATE_ARGS18
#undef IUTEST_FUNCTION_TEMPLATE_ARGS19
#undef IUTEST_FUNCTION_TEMPLATE_ARGS20

#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS1
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS2
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS3
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS4
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS5
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS6
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS7
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS8
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS9
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS10
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS11
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS12
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS13
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS14
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS15
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS16
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS17
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS18
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS19
#undef IUTEST_FUNCTION_TEMPLATE_FUNCTION_ARGS20

#undef IUTEST_FUNCTION_TEMPLATE_VALUES1
#undef IUTEST_FUNCTION_TEMPLATE_VALUES2
#undef IUTEST_FUNCTION_TEMPLATE_VALUES3
#undef IUTEST_FUNCTION_TEMPLATE_VALUES4
#undef IUTEST_FUNCTION_TEMPLATE_VALUES5
#undef IUTEST_FUNCTION_TEMPLATE_VALUES6
#undef IUTEST_FUNCTION_TEMPLATE_VALUES7
#undef IUTEST_FUNCTION_TEMPLATE_VALUES8
#undef IUTEST_FUNCTION_TEMPLATE_VALUES9
#undef IUTEST_FUNCTION_TEMPLATE_VALUES10
#undef IUTEST_FUNCTION_TEMPLATE_VALUES11
#undef IUTEST_FUNCTION_TEMPLATE_VALUES12
#undef IUTEST_FUNCTION_TEMPLATE_VALUES13
#undef IUTEST_FUNCTION_TEMPLATE_VALUES14
#undef IUTEST_FUNCTION_TEMPLATE_VALUES15
#undef IUTEST_FUNCTION_TEMPLATE_VALUES16
#undef IUTEST_FUNCTION_TEMPLATE_VALUES17
#undef IUTEST_FUNCTION_TEMPLATE_VALUES18
#undef IUTEST_FUNCTION_TEMPLATE_VALUES19
#undef IUTEST_FUNCTION_TEMPLATE_VALUES20

#ifdef INCG_IRIS_iutest_function_traits_defs_H_
#  undef INCG_IRIS_iutest_function_traits_defs_H_
#endif

#endif
