# Usage
# docker build --build-arg VERSION=release-1.8.0 -f .ci/Dockerfile.ref.gtest -t gtest .
# docker run -itd -v $(pwd):/iutest gtest bash

ARG VERSION=latest
FROM srzzumix/googletest:${VERSION}

LABEL maintainer "srz_zumix <https://github.com/srz-zumix>"

ARG VERSION
RUN echo ${VERSION} | tee image_version
VOLUME /iutest
WORKDIR /iutest

