name: 'Info'
description: 'print compiler/environment info'
inputs:
  before-clean:
    description: 'before clean'
    default: "true"
runs:
  using: "composite"
  steps:
    - name: clean
      shell: bash
      run: |
        make -C test clean
      if: ${{ inputs.before-clean }}
    - name: compiler info
      shell: bash
      run: |
        make -C test showcxxversion
        make -C test showcxxmacros
    - name: stdlib
      shell: bash
      run: |
        make -C test check_stdlib
