name: 'Info'
description: 'print compiler/environment info'
inputs:
  before-clean:
    description: 'before clean'
    default: true
runs:
  using: "composite"
  steps:
    - name: clean
      run: |
        make -C test clean
      if: ${{ inputs.before-clean }}
    - name: compiler info
      run: |
        make -C test showcxxversion
        make -C test showcxxmacros
    - name: stdlib
      run: |
        make -C test check_stdlib
