name: 'Info'
description: 'print compiler/environment info'
inputs:
  before-clean:
    description: 'before clean'
    default: "true"
  shell-cmd:
    description: 'shell command'
    default: "bash"

runs:
  using: "composite"
  steps:
    - name: clean
      shell: ${{ inputs.shell-cmd }}
      if: ${{ inputs.before-clean }}
      run: |
        make -C test clean
    - name: compiler info
      shell: ${{ inputs.shell-cmd }}
      run: |
        make -C test showcxxversion
        make -C test showcxxmacros
    - name: stdlib
      shell: ${{ inputs.shell-cmd }}
      run: |
        make -C test check_stdlib
    - name: stdlib features
      shell: ${{ inputs.shell-cmd }}
      run: |
        make -C test showstdlbfeatures
