name: 'Test Report'
description: 'test report'
inputs:
  report_paths:
    description: 'test report path'
    required: true

runs:
  using: "composite"
  steps:
    - name: report
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: ${{ inputs.report_paths }}
    - name: Test Summary
      uses: test-summary/action@v1
      with:
        paths:  ${{ inputs.report_paths }}
