# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

# config jobs template
parameters:
  name: ''
  options: ''
  vmImage: 'ubuntu-latest'

jobs:
  - job: ${{ parameters.name }}
    strategy:
      matrix:
        # mix config
        Conf_RandomEngine:
          MIX_CONFIG: "-DIUTEST_USE_RANDOM_ENGINE_TYPENAME=::std::default_random_engine"
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
    - template: template-make-test-steps.yml
      parameters:
        options: ${{ parameters.options }} DEFS+="${DEF_CONFIG}" ${ADD_OPT}
        package_name: "${{ parameters.name }}-${NOFEATURE_CONFIG}"
