# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

# disable config jobs template
parameters:
  name: ''
  options: ''
  vmImage: 'ubuntu 16.04'

jobs:
  - job: ${{ parameters.name }}
    strategy:
      matrix:
        # no feature config
        No_PrivateInAggregate:
          NOFEATURE_CONFIG: IUTEST_NO_PRIVATE_IN_AGGREGATE
        No_ArgumentDependentLookup:
          NOFEATURE_CONFIG: IUTEST_NO_ARGUMENT_DEPENDENT_LOOKUP
        No_VoidReturn:
          NOFEATURE_CONFIG: IUTEST_NO_VOID_RETURNS
        No_TemplateTemplates:
          NOFEATURE_CONFIG: IUTEST_NO_TEMPLATE_TEMPLATES
        No_TemplatePartialSpecialization:
          NOFEATURE_CONFIG: IUTEST_NO_TEMPLATE_PARTIAL_SPECIALIZATION
        No_VariadicMacro:
          NOFEATURE_CONFIG: IUTEST_NO_VARIADIC_MACROS
        No_SFINAE:
          NOFEATURE_CONFIG: IUTEST_NO_SFINAE
        Remove_LegacyTestCaseApi:
          NOFEATURE_CONFIG: IUTEST_REMOVE_LEGACY_TEST_CASEAPI_
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
    - template: template-make-test-steps.yml
      parameters:
        options: ${{ parameters.options }} DEFS+=-D${NOFEATURE_CONFIG} STDFLAG=-std=c++98
        package_name: "${{ parameters.name }}-${NOFEATURE_CONFIG}"
