# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

# template steps

parameters:
  target: ''
  vmImage: 'ubuntu-latest'

# target
# sh 'make disable_feature_param'
# sh 'make disable_feature_1'
# sh 'make disable_spec'
# sh 'make combine'
# sh 'make nofeature'

jobs:
  - job: ${{ parameters.target }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
    - script: make -C test/configcheck ${{ parameters.target }}
      displayName: 'test'
