FROM ubuntu:trusty

MAINTAINER srz-zumix <zumix.cpp@gmail.com>

RUN apt-get update -q -y
RUN apt-get install -y wget vim iputils-ping
RUN apt-get install -y python2.7 python2.7-dev python-virtualenv
RUN apt-get install -y git
RUN apt-get install -y build-essential
RUN mkdir /iutest

