on:
  pull_request:
  push:
    branches:
      - master
      - develop
  schedule:
    - cron:  '0 0 * * *'

name: AsesomeBot
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      ASESOME_BOT_OPTION: --allow-redirect --allow-ssl --allow-dupe -t 60
    steps:
      - uses: actions/checkout@v3
      - name: Create Gemfile
        run: |
          {
            echo 'source "http://rubygems.org"'
            echo "gem 'awesome_bot'"
          } > Gemfile
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: check
        run: |
          # shellcheck disable=SC2086
          .ci/awesome_bot.sh README.md    ${ASESOME_BOT_OPTION}
