on:
  pull_request:
  push:
  schedule:
    - cron:  '0 0 * * *'

name: AsesomeBot
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      ASESOME_BOT_OPTION: --allow-redirect --allow-ssl --allow-dupe -t 60
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: install
        run: gem install awesome_bot
      - name: check
        run: |
          awesome_bot README.md    "${ASESOME_BOT_OPTION}"
