on:
  pull_request:
  push:
    branches:
      - master
      - develop
  schedule:
    - cron:  '0 0 * * *'

name: AsesomeBot
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      ASESOME_BOT_OPTION: --allow-redirect --allow-ssl --allow-dupe -t 60
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: install
        run: gem install awesome_bot
      - name: check
        run: |
          # shellcheck disable=SC2086
          .ci/awesome_bot.sh README.md    ${ASESOME_BOT_OPTION}
