name: Coverity Scan
on:
  push:
    branches:
      - master
      - 'coverity_scan/**'
  schedule:
    - cron: '0 20 * * 6'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Travis CI coverity_scan job migration
  coverity-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vapier/coverity-scan-action@v1
        with:
          project: srz-zumix/iutest
          email: zumix.cpp@gmail.com
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          build_language: cxx
          command: make -C test -j4 coverity_scan STDFLAG=-std=c++17
